---
- name: Setup personal VPC
  hosts: vpc
  vars_files:
    - "{{ playbook_dir }}/config.yml"
    - "{{ playbook_dir }}/secrets.yml"

  roles:
    - user_setup
    - ssh_hardening
    - firewall
    - system_services
